#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

function changed {
  git diff --name-only HEAD@{1} HEAD | grep "^$1" > /dev/null 2>&1
}

if changed 'yarn.lock'; then
  echo "📦 - 📦 - 📦 - 📦 - 📦 - 📦 - 📦 - 📦 - 📦 - 📦 - 📦"
  echo "📦 - 📦 - 📦 - 📦 - 📦 - 📦 - 📦 - 📦 - 📦 - 📦 - 📦"
  echo "📦 yarn.lock changed,"
  echo "📦 running 'yarn install' again for you"
	echo "📦 - 📦 - 📦 - 📦 - 📦 - 📦 - 📦 - 📦 - 📦 - 📦 - 📦"
  echo "📦 - 📦 - 📦 - 📦 - 📦 - 📦 - 📦 - 📦 - 📦 - 📦 - 📦"

	yarn install
fi
